from pathlib import Path
import sys

root = Path(sys.argv[1]) if len(sys.argv) > 1 else Path('.')

def replace_exact(path: Path, old: str, new: str, count: int | None = None):
    text = path.read_text()
    found = text.count(old)
    expected = count if count is not None else 1
    if found != expected:
        raise SystemExit(f'{path}: expected {expected} occurrences, found {found}: {old[:100]!r}')
    path.write_text(text.replace(old, new))

login = root / 'src/components/Login.tsx'
replace_exact(login, "import { useToast } from '../context/ToastContext.tsx';\n", "import { useToast } from '../context/ToastContext.tsx';\nimport { useTheme } from '../context/ThemeContext.tsx';\n")
replace_exact(login, "  const { error: toastError } = useToast();\n", "  const { error: toastError } = useToast();\n  const { dormName, logoDataUri } = useTheme();\n")
replace_exact(login, "'border-transparent focus:border-[#1DB954] focus:bg-white'", "'border-transparent focus:border-[var(--brand-primary)] focus:bg-white'", 2)
replace_exact(login, 'bg-[#1DB954]/5', 'bg-[var(--brand-soft)]', 2)
replace_exact(login, '''        <div className="inline-flex items-center justify-center w-16 h-16 rounded-2xl bg-[#1DB954] p-0.5 mb-6">\n          <div className="w-full h-full bg-white rounded-[14px] flex items-center justify-center">\n            <Building2 className="w-8 h-8 text-[#1DB954]" />\n          </div>\n        </div>\n\n        {/* Headings */}\n        <h1 className="text-3xl font-extrabold tracking-tight text-[#1A1A1A] sm:text-4xl">\n          ระบบจัดการค่าเช่าห้องพัก\n        </h1>''','''        <div className="inline-flex items-center justify-center w-16 h-16 rounded-2xl bg-[var(--brand-primary)] p-0.5 mb-6">\n          <div className="w-full h-full bg-white rounded-[14px] flex items-center justify-center overflow-hidden">\n            {logoDataUri ? (\n              <img src={logoDataUri} alt={`${dormName} logo`} className="w-full h-full object-contain p-1.5" />\n            ) : (\n              <Building2 className="w-8 h-8 text-[var(--brand-primary)]" />\n            )}\n          </div>\n        </div>\n\n        {/* Headings */}\n        <h1 className="text-3xl font-extrabold tracking-tight text-[#1A1A1A] sm:text-4xl">\n          {dormName}\n        </h1>''')
replace_exact(login, 'text-[#1DB954]', 'text-[var(--brand-primary)]', 5)
replace_exact(login, 'bg-[#1DB954] hover:bg-[#1ED760] disabled:bg-[#1DB954]/30 text-white', 'bg-[var(--brand-primary)] hover:bg-[var(--brand-primary-hover)] disabled:opacity-30 text-[var(--brand-contrast)]')
replace_exact(login, 'text-[var(--brand-primary)] hover:text-[#1ED760]', 'text-[var(--brand-primary)] hover:text-[var(--brand-primary-hover)]')

app = root / 'src/App.tsx'
replace_exact(app, "  const { theme, toggleTheme } = useTheme();", "  const { theme, toggleTheme, dormName, logoDataUri } = useTheme();")
replace_exact(app, 'text-[#1DB954] mb-3', 'text-[var(--brand-primary)] mb-3')
replace_exact(app, '''            <div className="p-2 rounded-xl bg-[#1DB954] text-[#1A1A1A] shadow-md">\n              <Building2 className="w-5 h-5 text-white" />\n            </div>\n            <div>\n              <h1 className="font-extrabold text-sm text-white tracking-wide uppercase">\n                {settings?.dormName || 'Greenville'}\n              </h1>\n              <p className="text-[10px] text-[#1DB954] font-bold uppercase tracking-wider">ระบบบิลอัจฉริยะ</p>\n            </div>''','''            <div className="w-9 h-9 rounded-xl bg-[var(--brand-primary)] text-[var(--brand-contrast)] shadow-md flex items-center justify-center overflow-hidden">\n              {logoDataUri ? (\n                <img src={logoDataUri} alt={`${dormName} logo`} className="w-full h-full object-contain bg-white p-1" />\n              ) : (\n                <Building2 className="w-5 h-5" />\n              )}\n            </div>\n            <div>\n              <h1 className="font-extrabold text-sm text-white tracking-wide uppercase">\n                {dormName}\n              </h1>\n              <p className="text-[10px] text-[var(--brand-primary)] font-bold uppercase tracking-wider">ระบบบิลอัจฉริยะ</p>\n            </div>''')
replace_exact(app, "? 'bg-emerald-500 text-white shadow-md shadow-emerald-950/20'", "? 'bg-[var(--brand-primary)] text-[var(--brand-contrast)] shadow-md shadow-black/20'", 2)
replace_exact(app, "<Icon className={`w-4 h-4 shrink-0 ${isActive ? 'text-white' : 'text-zinc-500'}`} />", "<Icon className={`w-4 h-4 shrink-0 ${isActive ? 'text-[var(--brand-contrast)]' : 'text-zinc-500'}`} />")
replace_exact(app, 'className="md:hidden border-b border-emerald-200/30 bg-cover', 'className="md:hidden border-b border-white/10 bg-cover')
replace_exact(app, '"linear-gradient(90deg, rgba(6, 78, 59, 0.94), rgba(15, 23, 42, 0.96)), url(\'/header-nav-background-v1.png\')"', '"linear-gradient(90deg, color-mix(in srgb, var(--brand-primary) 55%, #0f172a 45%), rgba(15, 23, 42, 0.96)), url(\'/header-nav-background-v1.png\')"')
replace_exact(app, '''          <div className="p-1.5 rounded-lg bg-[#1DB954] text-[#1A1A1A] shadow-sm">\n            <Building2 className="w-4 h-4 text-white" />\n          </div>\n          <div>\n            <h1 className="font-extrabold text-xs text-white">\n              {settings?.dormName || 'Greenville'}\n            </h1>\n            <p className="text-[8px] text-emerald-200 font-bold uppercase">ระบบคิดค่าเช่า</p>\n          </div>''','''          <div className="w-8 h-8 rounded-lg bg-[var(--brand-primary)] text-[var(--brand-contrast)] shadow-sm flex items-center justify-center overflow-hidden">\n            {logoDataUri ? (\n              <img src={logoDataUri} alt={`${dormName} logo`} className="w-full h-full object-contain bg-white p-1" />\n            ) : (\n              <Building2 className="w-4 h-4" />\n            )}\n          </div>\n          <div>\n            <h1 className="font-extrabold text-xs text-white">\n              {dormName}\n            </h1>\n            <p className="text-[8px] text-[var(--brand-soft)] font-bold uppercase">ระบบคิดค่าเช่า</p>\n          </div>''')
replace_exact(app, 'className="w-64 h-full bg-cover bg-center p-5 border-r border-emerald-200/30', 'className="w-64 h-full bg-cover bg-center p-5 border-r border-white/10')
replace_exact(app, '"linear-gradient(180deg, rgba(6, 78, 59, 0.98), rgba(15, 23, 42, 0.99)), url(\'/header-nav-background-v1.png\')"', '"linear-gradient(180deg, color-mix(in srgb, var(--brand-primary) 58%, #0f172a 42%), rgba(15, 23, 42, 0.99)), url(\'/header-nav-background-v1.png\')"')
replace_exact(app, '''                  <div className="p-2 rounded-xl bg-[#1DB954] text-[#1A1A1A] shadow-md">\n                    <Building2 className="w-5 h-5 text-white" />\n                  </div>\n                  <div>\n                    <h1 className="font-extrabold text-xs text-white uppercase">{settings?.dormName || 'Greenville'}</h1>\n                    <p className="text-[9px] text-[#1DB954] font-semibold uppercase">Menu</p>\n                  </div>''','''                  <div className="w-9 h-9 rounded-xl bg-[var(--brand-primary)] text-[var(--brand-contrast)] shadow-md flex items-center justify-center overflow-hidden">\n                    {logoDataUri ? (\n                      <img src={logoDataUri} alt={`${dormName} logo`} className="w-full h-full object-contain bg-white p-1" />\n                    ) : (\n                      <Building2 className="w-5 h-5" />\n                    )}\n                  </div>\n                  <div>\n                    <h1 className="font-extrabold text-xs text-white uppercase">{dormName}</h1>\n                    <p className="text-[9px] text-[var(--brand-primary)] font-semibold uppercase">Menu</p>\n                  </div>''')
replace_exact(app, 'text-emerald-200/60', 'text-[var(--brand-soft)]/60')
replace_exact(app, "<Icon className={`w-4 h-4 shrink-0 ${isActive ? 'text-white' : 'text-emerald-200'}`} />", "<Icon className={`w-4 h-4 shrink-0 ${isActive ? 'text-[var(--brand-contrast)]' : 'text-[var(--brand-soft)]'}`} />")
replace_exact(app, 'bg-[#1DB954] animate-pulse', 'bg-[var(--brand-primary)] animate-pulse')
